name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Terraform Init (dev)
        run: terraform init -backend=false
        working-directory: terraform/envs/dev

      - name: Terraform Validate (dev)
        run: terraform validate
        working-directory: terraform/envs/dev

      - name: Terraform Init (prod)
        run: terraform init -backend=false
        working-directory: terraform/envs/prod

      - name: Terraform Validate (prod)
        run: terraform validate
        working-directory: terraform/envs/prod